# Generated by Django 3.2.8 on 2021-10-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('type', models.TextField(choices=[('AUDIO', 'Аудио'), ('VIDEO', 'Видео'), ('TEXT', 'Текст')], verbose_name='Тип контента')),
                ('count_views', models.IntegerField(default=0, editable=False, verbose_name='Количество просмотров')),
                ('additional_attributes', models.JSONField(default=dict, verbose_name='Дополнительные атрибуты')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='api.content', verbose_name='Контент')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='api.page', verbose_name='Странца')),
            ],
            options={
                'verbose_name': 'Связь страницы и контента',
                'unique_together': {('page', 'order')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.ManyToManyField(through='api.PageContent', to='api.Content'),
        ),
    ]
