# Generated by Django 3.2.8 on 2021-10-14 15:37

from django.core.management import call_command
from django.db import migrations


def add_data_from_fixture(apps, schema_editor):
    call_command('loaddata', 'api/fixture.json', verbosity=2)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data_from_fixture)
    ]
